// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Spawn.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_TURTLESIM_SRV_SPAWN_H_
#define _FAST_DDS_GENERATED_TURTLESIM_SRV_SPAWN_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(Spawn_SOURCE)
#define Spawn_DllAPI __declspec( dllexport )
#else
#define Spawn_DllAPI __declspec( dllimport )
#endif // Spawn_SOURCE
#else
#define Spawn_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define Spawn_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace turtlesim {
    namespace srv {
        /*!
         * @brief This class represents the structure Spawn_Request defined by the user in the IDL file.
         * @ingroup SPAWN
         */
        class Spawn_Request
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport Spawn_Request();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~Spawn_Request();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object turtlesim::srv::Spawn_Request that will be copied.
             */
            eProsima_user_DllExport Spawn_Request(
                    const Spawn_Request& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object turtlesim::srv::Spawn_Request that will be copied.
             */
            eProsima_user_DllExport Spawn_Request(
                    Spawn_Request&& x) noexcept;

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object turtlesim::srv::Spawn_Request that will be copied.
             */
            eProsima_user_DllExport Spawn_Request& operator =(
                    const Spawn_Request& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object turtlesim::srv::Spawn_Request that will be copied.
             */
            eProsima_user_DllExport Spawn_Request& operator =(
                    Spawn_Request&& x) noexcept;

            /*!
             * @brief Comparison operator.
             * @param x turtlesim::srv::Spawn_Request object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const Spawn_Request& x) const;

            /*!
             * @brief Comparison operator.
             * @param x turtlesim::srv::Spawn_Request object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const Spawn_Request& x) const;

            /*!
             * @brief This function sets a value in member x
             * @param _x New value for member x
             */
            eProsima_user_DllExport void x(
                    float _x);

            /*!
             * @brief This function returns the value of member x
             * @return Value of member x
             */
            eProsima_user_DllExport float x() const;

            /*!
             * @brief This function returns a reference to member x
             * @return Reference to member x
             */
            eProsima_user_DllExport float& x();

            /*!
             * @brief This function sets a value in member y
             * @param _y New value for member y
             */
            eProsima_user_DllExport void y(
                    float _y);

            /*!
             * @brief This function returns the value of member y
             * @return Value of member y
             */
            eProsima_user_DllExport float y() const;

            /*!
             * @brief This function returns a reference to member y
             * @return Reference to member y
             */
            eProsima_user_DllExport float& y();

            /*!
             * @brief This function sets a value in member theta
             * @param _theta New value for member theta
             */
            eProsima_user_DllExport void theta(
                    float _theta);

            /*!
             * @brief This function returns the value of member theta
             * @return Value of member theta
             */
            eProsima_user_DllExport float theta() const;

            /*!
             * @brief This function returns a reference to member theta
             * @return Reference to member theta
             */
            eProsima_user_DllExport float& theta();

            /*!
             * @brief This function copies the value in member name
             * @param _name New value to be copied in member name
             */
            eProsima_user_DllExport void name(
                    const std::string& _name);

            /*!
             * @brief This function moves the value in member name
             * @param _name New value to be moved in member name
             */
            eProsima_user_DllExport void name(
                    std::string&& _name);

            /*!
             * @brief This function returns a constant reference to member name
             * @return Constant reference to member name
             */
            eProsima_user_DllExport const std::string& name() const;

            /*!
             * @brief This function returns a reference to member name
             * @return Reference to member name
             */
            eProsima_user_DllExport std::string& name();

            /*!
            * @brief This function returns the maximum serialized size of an object
            * depending on the buffer alignment.
            * @param current_alignment Buffer alignment.
            * @return Maximum serialized size.
            */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const turtlesim::srv::Spawn_Request& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            float m_x;
            float m_y;
            float m_theta;
            std::string m_name;

        };
        /*!
         * @brief This class represents the structure Spawn_Response defined by the user in the IDL file.
         * @ingroup SPAWN
         */
        class Spawn_Response
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport Spawn_Response();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~Spawn_Response();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object turtlesim::srv::Spawn_Response that will be copied.
             */
            eProsima_user_DllExport Spawn_Response(
                    const Spawn_Response& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object turtlesim::srv::Spawn_Response that will be copied.
             */
            eProsima_user_DllExport Spawn_Response(
                    Spawn_Response&& x) noexcept;

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object turtlesim::srv::Spawn_Response that will be copied.
             */
            eProsima_user_DllExport Spawn_Response& operator =(
                    const Spawn_Response& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object turtlesim::srv::Spawn_Response that will be copied.
             */
            eProsima_user_DllExport Spawn_Response& operator =(
                    Spawn_Response&& x) noexcept;

            /*!
             * @brief Comparison operator.
             * @param x turtlesim::srv::Spawn_Response object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const Spawn_Response& x) const;

            /*!
             * @brief Comparison operator.
             * @param x turtlesim::srv::Spawn_Response object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const Spawn_Response& x) const;

            /*!
             * @brief This function copies the value in member name
             * @param _name New value to be copied in member name
             */
            eProsima_user_DllExport void name(
                    const std::string& _name);

            /*!
             * @brief This function moves the value in member name
             * @param _name New value to be moved in member name
             */
            eProsima_user_DllExport void name(
                    std::string&& _name);

            /*!
             * @brief This function returns a constant reference to member name
             * @return Constant reference to member name
             */
            eProsima_user_DllExport const std::string& name() const;

            /*!
             * @brief This function returns a reference to member name
             * @return Reference to member name
             */
            eProsima_user_DllExport std::string& name();

            /*!
            * @brief This function returns the maximum serialized size of an object
            * depending on the buffer alignment.
            * @param current_alignment Buffer alignment.
            * @return Maximum serialized size.
            */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const turtlesim::srv::Spawn_Response& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            std::string m_name;

        };
    } // namespace srv
} // namespace turtlesim

#endif // _FAST_DDS_GENERATED_TURTLESIM_SRV_SPAWN_H_