/*******************************************************************************
 * Copyright (c) 2026 HR Agartechnik GmbH
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Franz Höpfinger
 *     - implement Generic GEN_E_REND_fbt
 *******************************************************************************/

// Some portions generated by Gemini CLI

#include "forte/iec61499/events/GEN_E_REND_fbt.h"
#include "forte/util/string_utils.h"

using namespace forte::literals;

namespace forte::iec61499::events {
  // Registers the generic FB with the name "GEN_E_REND" in the FORTE type library.
  DEFINE_GENERIC_FIRMWARE_FB(GEN_E_REND, "iec61499::events::GEN_E_REND"_STRID)

  namespace {
    // Defines the constant name for the single event output.
    const auto cEventOutputNames = std::array{"EO"_STRID};
  } // namespace

  GEN_E_REND::GEN_E_REND(const StringId paInstanceNameId, CFBContainer &paContainer) :
      CGenFunctionBlock<CFunctionBlock>(paContainer, paInstanceNameId),
      mNumEIs(0),
      conn_EO(*this, 0) {
  }

  void GEN_E_REND::executeEvent(const TEventID paEIID, CEventChainExecutionThread *const paECET) {
    if (paEIID == mNumEIs) {
      // This is the R (Reset) event
      std::fill(mFlags.begin(), mFlags.end(), false);
    } else if (paEIID < mNumEIs) {
      // This is one of the EI inputs
      mFlags[paEIID] = true;

      // Check if all inputs have been received
      bool allReceived = true;
      for (bool received : mFlags) {
        if (!received) {
          allReceived = false;
          break;
        }
      }

      if (allReceived) {
        // Send EO
        sendOutputEvent(0, paECET);
        // Reset flags after rendezvous
        std::fill(mFlags.begin(), mFlags.end(), false);
      }
    }
  }

  void GEN_E_REND::readInputData(TEventID) {
    // Nothing to do, as there are no data inputs.
  }

  void GEN_E_REND::writeOutputData(TEventID) {
    // Nothing to do, as there are no data outputs.
  }

  bool GEN_E_REND::createInterfaceSpec(const char *paConfigString, SFBInterfaceSpec &paInterfaceSpec) {
    // Find the last underscore in the name, e.g., "E_REND_3".
    const char *acPos = strrchr(paConfigString, '_');

    if (nullptr != acPos) {
      ++acPos; // Move pointer to the character after the underscore.

      // Convert the numeric part to an integer. This is the number of EI inputs.
      mNumEIs = static_cast<size_t>(util::strtoul(acPos, nullptr, 10));

      // Check if the number of inputs is within the valid range.
      // E_REND needs at least 2 inputs. scmMaxInterfaceEvents is the hard limit.
      // We add 1 for R, so mNumEIs + 1 must be <= scmMaxInterfaceEvents.
      if (mNumEIs >= 2 && (mNumEIs + 1) < scmMaxInterfaceEvents) {

        // Resize flags vector to match number of inputs
        mFlags.resize(mNumEIs, false);

        mEventInputNames.clear();
        // Generate names "EI1", "EI2", etc.
        generateGenericInterfacePointNameArray("EI", mEventInputNames, mNumEIs);

        // Add the Reset input "R"
        mEventInputNames.push_back("R"_STRID);

        // Assign the generated input names and the constant output name to the interface.
        paInterfaceSpec.mEINames = mEventInputNames;
        paInterfaceSpec.mEONames = cEventOutputNames;

        return true; // Success
      } else {
        // Log errors if the number is out of bounds.
        if ((mNumEIs + 1) >= scmMaxInterfaceEvents) {
          DEVLOG_ERROR("Cannot configure FB-Instance GEN_E_REND_%d. Number of event inputs exceeds maximum of %d.\n",
                       mNumEIs, CFunctionBlock::scmMaxInterfaceEvents - 1);
        } else {
          DEVLOG_ERROR(
              "Cannot configure FB-Instance GEN_E_REND_%d. Number of event inputs smaller than minimum of 2.\n",
              mNumEIs);
        }
      }
    }
    return false; // Failure
  }

  // The following functions return nullptr because this FB does not handle data.
  CIEC_ANY *GEN_E_REND::getDI(size_t) {
    return nullptr;
  }

  CIEC_ANY *GEN_E_REND::getDO(size_t) {
    return nullptr;
  }

  CEventConnection *GEN_E_REND::getEOConUnchecked(const TPortId paIndex) {
    switch (paIndex) {
      case 0: return &conn_EO;
    }
    return nullptr;
  }

  CDataConnection **GEN_E_REND::getDIConUnchecked(TPortId) {
    return nullptr;
  }

  CDataConnection *GEN_E_REND::getDOConUnchecked(TPortId) {
    return nullptr;
  }
} // namespace forte::iec61499::events
