/*******************************************************************************
 * Copyright (c) 2023 ACIN, Primetals Technologies Austria GmbH
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Alois Zoitl - initial API and implementation and/or initial documentation
 *******************************************************************************/

#ifndef _START_UP_HOOK_H_
#define _START_UP_HOOK_H_


/*! \brief Startup hook function which will be called before devices are created and started.
 *
 * The implementation of this function is generated by cmake. Modules can register a call back
 * function which will be inserted into the body of this function. For that they can use the
 * forte_add_startup_hook() cmake macro.
 *
 * The call back functions shall have the following signature:
 *     void myStartupCallBack(int argc, char *arg[]);
 */
void startupHook(int argc, char *arg[]);

#endif
