/*******************************************************************************
 * Copyright (c) 2010 TU Vienna/ACIN, Profactor GmbH, fortiss GmbH
 *                    Primetals Technologies Austria GmbH
 *                    Martin Erich Jobst
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *    Alois Zoitl, Monika Wenger, Ingo Hegny, Patrick Smejkal, Gerhard Ebenhofer,
 *    Matthias Plasch, Martin Melik Merkumians
 *      - initial implementation and rework communication infrastructure
 *    Martin Melik Merkumians
 *      - added different type templates for IEC 61131-3 functions and adds several type guards
 *      - Reworked binary operator templates to create correctly calculated and typed results
 *      - reworked and fixes ADD and SUB for time types
 *      - Added variadic comparison, MIN, MAX, ADD, MUL functions
 *      - Added unary plus function
 *    Martin Erich Jobst
 *      - added lower and upper bound functions
 *    Franz Höpfinger
 *      - Support generic array types and generic integer types
 *******************************************************************************/

// Some portions generated by Claude

#pragma once

#include "forte/datatypes/forte_any_int.h"
#include "forte/datatypes/forte_array_common.h"
#include "forte/datatypes/forte_any_derived_variant.h"
#include "forte/datatypes/forte_dint.h"

namespace forte {
  template<typename T, typename U>
  T func_LOWER_BOUND(const CIEC_ARRAY &paArray, const U &paDimension) {
    static_assert(std::is_base_of_v<CIEC_ANY_INT, T>, "T not of ANY_INT");
    static_assert(std::is_base_of_v<CIEC_ANY_INT, U>, "U not of ANY_INT");
    intmax_t bound;
    if constexpr (is_generic_datatype_v<U>) {
      bound = paArray.getLowerBound(paDimension.unwrap().getSignedValue());
    } else {
      bound = paArray.getLowerBound(static_cast<typename U::TValueType>(paDimension));
    }
    if constexpr (is_generic_datatype_v<T>) {
      return T(CIEC_DINT(static_cast<CIEC_DINT::TValueType>(bound)));
    } else {
      return T(static_cast<typename T::TValueType>(bound));
    }
  }

  template<typename T, typename U>
  T func_LOWER_BOUND(const CIEC_ANY_DERIVED_VARIANT &paArray, const U &paDimension) {
    return func_LOWER_BOUND<T>(static_cast<const CIEC_ARRAY &>(paArray.unwrap()), paDimension);
  }

} // namespace forte
