// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file GoalStatus.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_ACTION_MSGS_MSG_GOALSTATUS_H_
#define _FAST_DDS_GENERATED_ACTION_MSGS_MSG_GOALSTATUS_H_

#include "GoalInfo.h"

#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(GoalStatus_SOURCE)
#define GoalStatus_DllAPI __declspec( dllexport )
#else
#define GoalStatus_DllAPI __declspec( dllimport )
#endif // GoalStatus_SOURCE
#else
#define GoalStatus_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define GoalStatus_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace action_msgs {
    namespace msg {
        namespace GoalStatus_Constants {
            const int8_t STATUS_UNKNOWN = 0;
            const int8_t STATUS_ACCEPTED = 1;
            const int8_t STATUS_EXECUTING = 2;
            const int8_t STATUS_CANCELING = 3;
            const int8_t STATUS_SUCCEEDED = 4;
            const int8_t STATUS_CANCELED = 5;
            const int8_t STATUS_ABORTED = 6;
        } // namespace GoalStatus_Constants
        /*!
         * @brief This class represents the structure GoalStatus defined by the user in the IDL file.
         * @ingroup GOALSTATUS
         */
        class GoalStatus
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport GoalStatus();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~GoalStatus();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object action_msgs::msg::GoalStatus that will be copied.
             */
            eProsima_user_DllExport GoalStatus(
                    const GoalStatus& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object action_msgs::msg::GoalStatus that will be copied.
             */
            eProsima_user_DllExport GoalStatus(
                    GoalStatus&& x) noexcept;

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object action_msgs::msg::GoalStatus that will be copied.
             */
            eProsima_user_DllExport GoalStatus& operator =(
                    const GoalStatus& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object action_msgs::msg::GoalStatus that will be copied.
             */
            eProsima_user_DllExport GoalStatus& operator =(
                    GoalStatus&& x) noexcept;

            /*!
             * @brief Comparison operator.
             * @param x action_msgs::msg::GoalStatus object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const GoalStatus& x) const;

            /*!
             * @brief Comparison operator.
             * @param x action_msgs::msg::GoalStatus object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const GoalStatus& x) const;

            /*!
             * @brief This function copies the value in member goal_info
             * @param _goal_info New value to be copied in member goal_info
             */
            eProsima_user_DllExport void goal_info(
                    const action_msgs::msg::GoalInfo& _goal_info);

            /*!
             * @brief This function moves the value in member goal_info
             * @param _goal_info New value to be moved in member goal_info
             */
            eProsima_user_DllExport void goal_info(
                    action_msgs::msg::GoalInfo&& _goal_info);

            /*!
             * @brief This function returns a constant reference to member goal_info
             * @return Constant reference to member goal_info
             */
            eProsima_user_DllExport const action_msgs::msg::GoalInfo& goal_info() const;

            /*!
             * @brief This function returns a reference to member goal_info
             * @return Reference to member goal_info
             */
            eProsima_user_DllExport action_msgs::msg::GoalInfo& goal_info();
            /*!
             * @brief This function sets a value in member status
             * @param _status New value for member status
             */
            eProsima_user_DllExport void status(
                    int8_t _status);

            /*!
             * @brief This function returns the value of member status
             * @return Value of member status
             */
            eProsima_user_DllExport int8_t status() const;

            /*!
             * @brief This function returns a reference to member status
             * @return Reference to member status
             */
            eProsima_user_DllExport int8_t& status();


            /*!
            * @brief This function returns the maximum serialized size of an object
            * depending on the buffer alignment.
            * @param current_alignment Buffer alignment.
            * @return Maximum serialized size.
            */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const action_msgs::msg::GoalStatus& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            action_msgs::msg::GoalInfo m_goal_info;
            int8_t m_status;

        };
    } // namespace msg
} // namespace action_msgs

#endif // _FAST_DDS_GENERATED_ACTION_MSGS_MSG_GOALSTATUS_H_