/*******************************************************************************
 * Copyright (c) 2026 HR Agartechnik GmbH
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Franz Höpfinger
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

// Some portions generated by Gemini CLI

#include "../../../core/fbtests/fbtestfixture.h"
#include "forte/eclipse4diac/rtevents/rtesingle.h"
#include "forte/datatypes/forte_bool.h"
#include "forte/datatypes/forte_time.h"

using namespace forte::literals;

#include <chrono>

#ifdef WIN32
#include <windows.h>
#define usleep(x) Sleep((x) / 1000)
#else
#include <unistd.h>
#endif

namespace forte::eclipse4diac::rtevents::test {
  struct RT_E_REND_TestFixture : public forte::test::CFBTestFixtureBase {
      static constexpr TEventID INIT = 0;
      static constexpr TEventID EI1 = 1;
      static constexpr TEventID EI2 = 2;
      static constexpr TEventID R = 3;
      static constexpr TEventID INITO = 0;
      static constexpr TEventID EO = 1;

      RT_E_REND_TestFixture() : CFBTestFixtureBase("eclipse4diac::rtevents::RT_E_REND"_STRID) {
        setInputData({&mQI, &mTmin, &mDeadline, &mWCET});
        setOutputData({&mQO});
        setup();
        mInternalECET = &static_cast<CRTEventSingle *>(getFBUnderTest())->getInternalEventChain();
      }

      // We need a helper to wait for asynchronous events generated by the internal thread
      bool waitForInternalThreadEvent(TEventID expectedEvent, int maxWaitMs = 100) {
        auto deadline = std::chrono::steady_clock::now() + std::chrono::milliseconds(maxWaitMs);
        do {
          if (!eventChainEmpty()) {
            return checkForSingleOutputEventOccurence(expectedEvent);
          }
          do {
            usleep(1);
          } while (mInternalECET->isProcessingEvents());
          usleep(1000);
        } while (std::chrono::steady_clock::now() < deadline);
        return checkForSingleOutputEventOccurence(expectedEvent);
      }

      CEventChainExecutionThread *mInternalECET = nullptr;
      CIEC_BOOL mQI;
      CIEC_TIME mTmin;
      CIEC_TIME mDeadline;
      CIEC_TIME mWCET;
      CIEC_BOOL mQO;
  };

  BOOST_FIXTURE_TEST_SUITE(RTERendTests, RT_E_REND_TestFixture)

  BOOST_AUTO_TEST_CASE(Initialization) {
    mQI = true_BOOL;
    mDeadline = 1000_TIME; // Some dummy deadline
    triggerEvent(INIT);
    BOOST_CHECK(checkForSingleOutputEventOccurence(INITO));
    BOOST_CHECK_EQUAL(mQO, true_BOOL);
  }

  BOOST_AUTO_TEST_CASE(Rendezvous_EI1_Then_EI2) {
    mQI = true_BOOL;
    triggerEvent(INIT);
    BOOST_CHECK(checkForSingleOutputEventOccurence(INITO));

    triggerEvent(EI1);
    BOOST_CHECK(eventChainEmpty());

    triggerEvent(EI2);
    // Expected async EO (index 1)
    BOOST_CHECK(waitForInternalThreadEvent(EO));
  }

  BOOST_AUTO_TEST_CASE(Rendezvous_EI2_Then_EI1) {
    mQI = true_BOOL;
    triggerEvent(INIT);
    BOOST_CHECK(checkForSingleOutputEventOccurence(INITO));

    triggerEvent(EI2);
    BOOST_CHECK(eventChainEmpty());

    triggerEvent(EI1);
    // Expected async EO (index 1)
    BOOST_CHECK(waitForInternalThreadEvent(EO));
  }

  BOOST_AUTO_TEST_CASE(Reset_From_EI1) {
    mQI = true_BOOL;
    triggerEvent(INIT);
    BOOST_CHECK(checkForSingleOutputEventOccurence(INITO));

    triggerEvent(EI1);
    BOOST_CHECK(eventChainEmpty());

    // Trigger Reset (R) which is index 3
    triggerEvent(R);
    BOOST_CHECK(eventChainEmpty());

    // After reset, triggering the other one (EI2) should not cause EO
    triggerEvent(EI2);
    BOOST_CHECK(!waitForInternalThreadEvent(EO, 10)); // wait up to 10ms to ensure it didn't trigger
    BOOST_CHECK(eventChainEmpty()); // Double check

    // Triggering EI1 now should cause EO
    triggerEvent(EI1);
    BOOST_CHECK(waitForInternalThreadEvent(EO));
  }

  BOOST_AUTO_TEST_CASE(Reset_From_EI2) {
    mQI = true_BOOL;
    triggerEvent(INIT);
    BOOST_CHECK(checkForSingleOutputEventOccurence(INITO));

    triggerEvent(EI2);
    BOOST_CHECK(eventChainEmpty());

    // Trigger Reset (R) which is index 3
    triggerEvent(R);
    BOOST_CHECK(eventChainEmpty());

    // After reset, triggering the other one (EI1) should not cause EO
    triggerEvent(EI1);
    BOOST_CHECK(!waitForInternalThreadEvent(EO, 10));
    BOOST_CHECK(eventChainEmpty());

    // Triggering EI2 now should cause EO
    triggerEvent(EI2);
    BOOST_CHECK(waitForInternalThreadEvent(EO));
  }

  BOOST_AUTO_TEST_CASE(Multiple_EI1_Then_Multiple_EI2) {
    mQI = true_BOOL;
    triggerEvent(INIT);
    BOOST_CHECK(checkForSingleOutputEventOccurence(INITO));

    triggerEvent(EI1);
    BOOST_CHECK(eventChainEmpty());
    triggerEvent(EI1);
    BOOST_CHECK(eventChainEmpty());
    triggerEvent(EI1);
    BOOST_CHECK(eventChainEmpty());

    // First EI2 completes the rendezvous
    triggerEvent(EI2);
    BOOST_CHECK(waitForInternalThreadEvent(EO));

    // Subsequent EI2s without a new EI1 should not fire EO
    triggerEvent(EI2);
    BOOST_CHECK(!waitForInternalThreadEvent(EO, 10));
    BOOST_CHECK(eventChainEmpty());
    triggerEvent(EI2);
    BOOST_CHECK(!waitForInternalThreadEvent(EO, 10));
    BOOST_CHECK(eventChainEmpty());
  }

  BOOST_AUTO_TEST_CASE(Multiple_Rendezvous) {
    mQI = true_BOOL;
    triggerEvent(INIT);
    BOOST_CHECK(checkForSingleOutputEventOccurence(INITO));

    for (int i = 0; i < 5; i++) {
      triggerEvent(EI1);
      BOOST_CHECK(eventChainEmpty());
      triggerEvent(EI2);
      BOOST_CHECK(waitForInternalThreadEvent(EO));
    }
  }

  BOOST_AUTO_TEST_CASE(Deadline_Parameter_Test) {
    // Note: In FORTE, the Deadline parameter is passed to the underlying thread
    // for RTOS scheduling (e.g. Earliest Deadline First). An "overflow" (missing
    // the deadline) does not abort the thread or generate an error event in the FB
    // itself. Here we just test that setting a very strict or 0 deadline does
    // not break the functional behavior of the Rendezvous.
    mQI = true_BOOL;
    mDeadline = 1_TIME; // Very short deadline
    mWCET = 1_TIME;
    mTmin = 1_TIME;
    triggerEvent(INIT);
    BOOST_CHECK(checkForSingleOutputEventOccurence(INITO));

    triggerEvent(EI1);
    BOOST_CHECK(eventChainEmpty());

    // Even if it takes longer than 1_TIME internally, it will still emit EO
    usleep(2000); // Wait 2ms (exceeding deadline)

    triggerEvent(EI2);
    BOOST_CHECK(waitForInternalThreadEvent(EO));
  }

  BOOST_AUTO_TEST_SUITE_END()
} // namespace forte::eclipse4diac::rtevents::test
