/*******************************************************************************
 * Copyright (c) 2019, fortiss GmbH
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Jose Cabral - initial implementation
 *******************************************************************************/

#include "SubscribeEventHTTP.h"

USE_STRING_ID(ANYToJSON);
USE_STRING_ID(APPEND_STRING_3);
USE_STRING_ID(CLIENT_1_2);
USE_STRING_ID(CNF);
USE_STRING_ID(CreateRegisterID);
USE_STRING_ID(CreateRegisterID_1);
USE_STRING_ID(EI);
USE_STRING_ID(endpoint);
USE_STRING_ID(EO);
USE_STRING_ID(E_PERMIT);
USE_STRING_ID(E_PERMIT_1);
USE_STRING_ID(E_SR);
USE_STRING_ID(eventFilter);
USE_STRING_ID(F_STRING_TO_WSTRING);
USE_STRING_ID(F_STRING_TO_WSTRING_2);
USE_STRING_ID(ID);
USE_STRING_ID(IN);
USE_STRING_ID(IN_1);
USE_STRING_ID(IN_2);
USE_STRING_ID(IN_3);
USE_STRING_ID(INIT);
USE_STRING_ID(InitFlagReg);
USE_STRING_ID(InitFlagUnReg);
USE_STRING_ID(INITO);
USE_STRING_ID(input);
USE_STRING_ID(OUT);
USE_STRING_ID(output);
USE_STRING_ID(PERMIT);
USE_STRING_ID(Q);
USE_STRING_ID(QI);
USE_STRING_ID(R);
USE_STRING_ID(Register);
USE_STRING_ID(REQ);
USE_STRING_ID(S);
USE_STRING_ID(SD_1);
USE_STRING_ID(Subscribe);
USE_STRING_ID(Subscribed);
USE_STRING_ID(SubscribeEventAdp);
USE_STRING_ID(SubscribeEventHTTP);
USE_STRING_ID(Unregister);
USE_STRING_ID(Unsubscribe);
USE_STRING_ID(Unsubscribed);


DEFINE_FIRMWARE_FB(FORTE_SubscribeEventHTTP, STRID(SubscribeEventHTTP))

const TForteInt16 FORTE_SubscribeEventHTTP::scmEOWithIndexes[] = {-1};
const SAdapterInstanceDef FORTE_SubscribeEventHTTP::scmAdapterInstances[] = {
{STRID(SubscribeEventAdp), STRID(SubscribeEventAdp), false }};

const SFBInterfaceSpec FORTE_SubscribeEventHTTP::scmFBInterfaceSpec = {
  0,  0, nullptr,  0,  0,
  0,  0, nullptr,   0, 0,  0,  0, 0, 
  0,  0, 0,
  1,scmAdapterInstances};


const SCFB_FBInstanceData FORTE_SubscribeEventHTTP::scmInternalFBs[] = {
  {STRID(InitFlagReg), STRID(E_SR)},
  {STRID(E_PERMIT), STRID(E_PERMIT)},
  {STRID(InitFlagUnReg), STRID(E_SR)},
  {STRID(F_STRING_TO_WSTRING), STRID(F_STRING_TO_WSTRING)},
  {STRID(CreateRegisterID), STRID(APPEND_STRING_3)},
  {STRID(ANYToJSON), STRID(ANYToJSON)},
  {STRID(E_PERMIT_1), STRID(E_PERMIT)},
  {STRID(Register), STRID(CLIENT_1_2)},
  {STRID(Unregister), STRID(CLIENT_1_2)},
  {STRID(CreateRegisterID_1), STRID(APPEND_STRING_3)},
  {STRID(F_STRING_TO_WSTRING_2), STRID(F_STRING_TO_WSTRING)},
};

const SCFB_FBParameter FORTE_SubscribeEventHTTP::scmParamters[] = {
  {4, STRID(IN_1), "STRING#http["},
  {4, STRID(IN_3), "STRING#/subscription; POST; application/json]"},
  {9, STRID(IN_1), "STRING#http["},
  {9, STRID(IN_3), "STRING#/subscription; PUT; application/json]"},
};

const SCFB_FBConnectionData FORTE_SubscribeEventHTTP::scmEventConnections[] = {
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Register), STRID(INITO)), 7, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_PERMIT), STRID(EI)), 1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Register), STRID(CNF)), 7, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(InitFlagReg), STRID(R)), 0},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(InitFlagReg), STRID(EO)), 0, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Register), STRID(INIT)), 7},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(CreateRegisterID), STRID(CNF)), 4, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(F_STRING_TO_WSTRING), STRID(REQ)), 3},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(F_STRING_TO_WSTRING), STRID(CNF)), 3, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(ANYToJSON), STRID(REQ)), 5},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_PERMIT), STRID(EO)), 1, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Register), STRID(REQ)), 7},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(SubscribeEventAdp), STRID(Subscribe)), CCompositeFB::scmAdapterMarker |0, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(CreateRegisterID), STRID(REQ)), 4},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(InitFlagUnReg), STRID(EO)), 2, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Unregister), STRID(INIT)), 8},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_PERMIT_1), STRID(EO)), 6, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Unregister), STRID(REQ)), 8},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Unregister), STRID(INITO)), 8, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_PERMIT_1), STRID(EI)), 6},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Unregister), STRID(CNF)), 8, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(SubscribeEventAdp), STRID(Unsubscribed)), CCompositeFB::scmAdapterMarker |0},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(SubscribeEventAdp), STRID(Unsubscribe)), CCompositeFB::scmAdapterMarker |0, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(CreateRegisterID_1), STRID(REQ)), 9},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(CreateRegisterID_1), STRID(CNF)), 9, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(F_STRING_TO_WSTRING_2), STRID(REQ)), 10},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(F_STRING_TO_WSTRING_2), STRID(CNF)), 10, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(ANYToJSON), STRID(REQ)), 5},
};

const SCFB_FBFannedOutConnectionData FORTE_SubscribeEventHTTP::scmFannedOutEventConnections[] = {
  {1, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(SubscribeEventAdp), STRID(Subscribed)), CCompositeFB::scmAdapterMarker |0},
  {4, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(InitFlagReg), STRID(S)), 0},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(InitFlagUnReg), STRID(R)), 2},
  {13, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(InitFlagUnReg), STRID(S)), 2},
};

const SCFB_FBConnectionData FORTE_SubscribeEventHTTP::scmDataConnections[] = {
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(InitFlagUnReg), STRID(Q)), 2, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_PERMIT_1), STRID(PERMIT)), 6},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(InitFlagReg), STRID(Q)), 0, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Register), STRID(QI)), 7},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(ANYToJSON), STRID(output)), 5, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Register), STRID(SD_1)), 7},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(CreateRegisterID), STRID(OUT)), 4, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(F_STRING_TO_WSTRING), STRID(IN)), 3},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(F_STRING_TO_WSTRING), STRID(OUT)), 3, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Register), STRID(ID)), 7},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(SubscribeEventAdp), STRID(endpoint)), CCompositeFB::scmAdapterMarker |0, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(CreateRegisterID), STRID(IN_2)), 4},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(SubscribeEventAdp), STRID(eventFilter)), CCompositeFB::scmAdapterMarker |0, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(ANYToJSON), STRID(input)), 5},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(CreateRegisterID_1), STRID(OUT)), 9, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(F_STRING_TO_WSTRING_2), STRID(IN)), 10},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(F_STRING_TO_WSTRING_2), STRID(OUT)), 10, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Unregister), STRID(ID)), 8},
};

const SCFB_FBFannedOutConnectionData FORTE_SubscribeEventHTTP::scmFannedOutDataConnections[] = {
  {0, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Unregister), STRID(QI)), 8},
  {1, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_PERMIT), STRID(PERMIT)), 1},
  {2, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Unregister), STRID(SD_1)), 8},
  {5, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(CreateRegisterID_1), STRID(IN_2)), 9},
};

const SCFB_FBNData FORTE_SubscribeEventHTTP::scmFBNData = {
  11, scmInternalFBs,
  14, scmEventConnections,
  4, scmFannedOutEventConnections,
  9, scmDataConnections,
  4, scmFannedOutDataConnections,
  0, nullptr,
  4, scmParamters
};


