/*******************************************************************************
 * Copyright (c) 2022 Patrick Aigner
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Patrick Aigner
 *
 * FILE GENERATED BY LUAJIT - DO NOT MODIFY
 * (except copy this header)
 *******************************************************************************/

#define luaJIT_BC_STfunc_SIZE 142
static const unsigned char luaJIT_BC_STfunc[] = {
27,76,74,2,10,15,0,2,3,0,0,0,2,32,2,1,0,76,2,2,0,15,0,2,3,0,0,0,2,33,2,1,0,76,
2,2,0,15,0,2,3,0,0,0,2,34,2,1,0,76,2,2,0,15,0,2,3,0,0,0,2,35,2,1,0,76,2,2,0,
71,3,0,2,0,8,0,11,52,0,0,0,51,1,1,0,61,1,0,0,51,1,3,0,61,1,2,0,51,1,5,0,61,1,
4,0,51,1,7,0,61,1,6,0,50,0,0,128,76,0,2,0,0,8,68,73,86,0,8,77,85,76,0,8,83,85,
66,0,8,65,68,68,0
};
