/*******************************************************************************
 * Copyright (c) 2026 HR Agartechnik GmbH
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Franz Höpfinger
 *     - implement Generic GEN_E_REND_fbt
 *******************************************************************************/

// Some portions generated by Gemini CLI

#pragma once

#include <vector>
#include "forte/genfb.h"
#include "forte/stringid.h"

namespace forte::iec61499::events {
  /**
   * @brief A generic function block for event rendezvous (synchronization).
   *
   * The number of event inputs is determined by the instance name, e.g., an instance
   * named "GEN_E_REND_3" will have 3 synchronization inputs (EI1, EI2, EI3) and one Reset input (R).
   * The output EO is fired only after all EI inputs have been received.
   */
  class GEN_E_REND final : public CGenFunctionBlock<CFunctionBlock> {
      DECLARE_GENERIC_FIRMWARE_FB(GEN_E_REND)

    private:
      /**
       * @brief Executes when an event is received.
       *
       * @param paEIID The ID of the input event that triggered the execution.
       * @param paECET The event chain execution thread.
       */
      void executeEvent(TEventID paEIID, CEventChainExecutionThread *const paECET) override;

      /** These functions are not needed as this FB has no data inputs/outputs. */
      void readInputData(TEventID paEIID) override;
      void writeOutputData(TEventID paEIID) override;

      /**
       * @brief Creates the interface specification based on the configuration string.
       *
       * It parses the number from the end of the config string (e.g., "3" from "GEN_E_REND_3")
       * to determine the number of event inputs.
       * @param paConfigString The configuration string (typically the FB instance name).
       * @param paInterfaceSpec The interface specification structure to be filled.
       * @return true on success, false otherwise.
       */
      bool createInterfaceSpec(const char *paConfigString, SFBInterfaceSpec &paInterfaceSpec) override;

      /** A vector to hold the dynamically generated StringIds for the event input names. */
      std::vector<StringId> mEventInputNames;

      /**
       * @brief Tracks which events have been received.
       * mFlags[i] corresponds to EI(i+1).
       */
      std::vector<bool> mFlags;

      /**
       * @brief Number of synchronization inputs (excluding R).
       * Set during configuration.
       */
      size_t mNumEIs;

    public:
      GEN_E_REND(StringId paInstanceNameId, CFBContainer &paContainer);

      CEventConnection conn_EO;

      CIEC_ANY *getDI(size_t) override;
      CIEC_ANY *getDO(size_t) override;
      CEventConnection *getEOConUnchecked(TPortId) override;
      CDataConnection **getDIConUnchecked(TPortId) override;
      CDataConnection *getDOConUnchecked(TPortId) override;
  };
} // namespace forte::iec61499::events
