/*******************************************************************************
 * Copyright (c) 2010,2025 TU Vienna/ACIN, Profactor GmbH, fortiss GmbH
 *                         Primetals Technologies Austria GmbH
 *                         Martin Erich Jobst
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *    Alois Zoitl, Monika Wenger, Ingo Hegny, Patrick Smejkal, Gerhard Ebenhofer,
 *    Matthias Plasch, Martin Melik Merkumians
 *      - initial implementation and rework communication infrastructure
 *    Martin Melik Merkumians
 *      - added different type templates for IEC 61131-3 functions and adds several type guards
 *      - Reworked binary operator templates to create correctly calculated and typed results
 *      - reworked and fixes ADD and SUB for time types
 *      - Added variadic comparison, MIN, MAX, ADD, MUL functions
 *      - Added unary plus function
 *    Martin Erich Jobst
 *      - added lower and upper bound functions
 *******************************************************************************/

#pragma once

#include "forte/forte_st_util.h"

#include "forte/datatypes/convert/convert_functions.h"

#include "forte/iec61131_functions/func_ABS.h"
#include "forte/iec61131_functions/func_ACOS.h"
#include "forte/iec61131_functions/func_ADD.h"
#include "forte/iec61131_functions/func_ADD_DT_TIME.h"
#include "forte/iec61131_functions/func_ADD_LDT_LTIME.h"
#include "forte/iec61131_functions/func_ADD_LTIME.h"
#include "forte/iec61131_functions/func_ADD_LTOD_LTIME.h"
#include "forte/iec61131_functions/func_ADD_TIME.h"
#include "forte/iec61131_functions/func_ADD_TOD_TIME.h"
#include "forte/iec61131_functions/func_AND.h"
#include "forte/iec61131_functions/func_ASIN.h"
#include "forte/iec61131_functions/func_ATAN.h"
#include "forte/iec61131_functions/func_ATAN2.h"
#include "forte/iec61131_functions/func_CONCAT.h"
#include "forte/iec61131_functions/func_CONCAT_DATE.h"
#include "forte/iec61131_functions/func_CONCAT_DATE_TOD.h"
#include "forte/iec61131_functions/func_CONCAT_DT.h"
#include "forte/iec61131_functions/func_CONCAT_LDATE.h"
#include "forte/iec61131_functions/func_CONCAT_LDATE_LTOD.h"
#include "forte/iec61131_functions/func_CONCAT_LDT.h"
#include "forte/iec61131_functions/func_CONCAT_LTOD.h"
#include "forte/iec61131_functions/func_CONCAT_TOD.h"
#include "forte/iec61131_functions/func_COS.h"
#include "forte/iec61131_functions/func_DAY_OF_WEEK.h"
#include "forte/iec61131_functions/func_DELETE.h"
#include "forte/iec61131_functions/func_DIV.h"
#include "forte/iec61131_functions/func_DIV_LTIME.h"
#include "forte/iec61131_functions/func_DIV_TIME.h"
#include "forte/iec61131_functions/func_EQ.h"
#include "forte/iec61131_functions/func_EXP.h"
#include "forte/iec61131_functions/func_EXPT.h"
#include "forte/iec61131_functions/func_FIND.h"
#include "forte/iec61131_functions/func_FROM_BIG_ENDIAN.h"
#include "forte/iec61131_functions/func_FROM_LITTLE_ENDIAN.h"
#include "forte/iec61131_functions/func_GE.h"
#include "forte/iec61131_functions/func_GT.h"
#include "forte/iec61131_functions/func_INSERT.h"
#include "forte/iec61131_functions/func_IS_VALID.h"
#include "forte/iec61131_functions/func_IS_VALID_BCD.h"
#include "forte/iec61131_functions/func_LE.h"
#include "forte/iec61131_functions/func_LEFT.h"
#include "forte/iec61131_functions/func_LEN.h"
#include "forte/iec61131_functions/func_LIMIT.h"
#include "forte/iec61131_functions/func_LN.h"
#include "forte/iec61131_functions/func_LOG.h"
#include "forte/iec61131_functions/func_LOWER_BOUND.h"
#include "forte/iec61131_functions/func_LREAL_TRUNC_DINT.h"
#include "forte/iec61131_functions/func_LREAL_TRUNC_INT.h"
#include "forte/iec61131_functions/func_LREAL_TRUNC_LINT.h"
#include "forte/iec61131_functions/func_LREAL_TRUNC_SINT.h"
#include "forte/iec61131_functions/func_LREAL_TRUNC_UDINT.h"
#include "forte/iec61131_functions/func_LREAL_TRUNC_UINT.h"
#include "forte/iec61131_functions/func_LREAL_TRUNC_ULINT.h"
#include "forte/iec61131_functions/func_LREAL_TRUNC_USINT.h"
#include "forte/iec61131_functions/func_LT.h"
#include "forte/iec61131_functions/func_MAX.h"
#include "forte/iec61131_functions/func_MID.h"
#include "forte/iec61131_functions/func_MIN.h"
#include "forte/iec61131_functions/func_MINUS.h"
#include "forte/iec61131_functions/func_MOD.h"
#include "forte/iec61131_functions/func_MOVE.h"
#include "forte/iec61131_functions/func_MUL.h"
#include "forte/iec61131_functions/func_MUL_LTIME.h"
#include "forte/iec61131_functions/func_MUL_TIME.h"
#include "forte/iec61131_functions/func_NE.h"
#include "forte/iec61131_functions/func_NOT.h"
#include "forte/iec61131_functions/func_NOW.h"
#include "forte/iec61131_functions/func_NOW_MONOTONIC.h"
#include "forte/iec61131_functions/func_OR.h"
#include "forte/iec61131_functions/func_PLUS.h"
#include "forte/iec61131_functions/func_REAL_TRUNC_DINT.h"
#include "forte/iec61131_functions/func_REAL_TRUNC_INT.h"
#include "forte/iec61131_functions/func_REAL_TRUNC_LINT.h"
#include "forte/iec61131_functions/func_REAL_TRUNC_SINT.h"
#include "forte/iec61131_functions/func_REAL_TRUNC_UDINT.h"
#include "forte/iec61131_functions/func_REAL_TRUNC_UINT.h"
#include "forte/iec61131_functions/func_REAL_TRUNC_ULINT.h"
#include "forte/iec61131_functions/func_REAL_TRUNC_USINT.h"
#include "forte/iec61131_functions/func_REPLACE.h"
#include "forte/iec61131_functions/func_RIGHT.h"
#include "forte/iec61131_functions/func_ROL.h"
#include "forte/iec61131_functions/func_ROR.h"
#include "forte/iec61131_functions/func_SEL.h"
#include "forte/iec61131_functions/func_SHL.h"
#include "forte/iec61131_functions/func_SHR.h"
#include "forte/iec61131_functions/func_SIN.h"
#include "forte/iec61131_functions/func_SPLIT_DATE.h"
#include "forte/iec61131_functions/func_SPLIT_DT.h"
#include "forte/iec61131_functions/func_SPLIT_LDATE.h"
#include "forte/iec61131_functions/func_SPLIT_LDT.h"
#include "forte/iec61131_functions/func_SPLIT_LTOD.h"
#include "forte/iec61131_functions/func_SPLIT_TOD.h"
#include "forte/iec61131_functions/func_SQRT.h"
#include "forte/iec61131_functions/func_SUB.h"
#include "forte/iec61131_functions/func_SUB_DATE_DATE.h"
#include "forte/iec61131_functions/func_SUB_DT_DT.h"
#include "forte/iec61131_functions/func_SUB_DT_TIME.h"
#include "forte/iec61131_functions/func_SUB_LDATE_LDATE.h"
#include "forte/iec61131_functions/func_SUB_LDT_LDT.h"
#include "forte/iec61131_functions/func_SUB_LDT_LTIME.h"
#include "forte/iec61131_functions/func_SUB_LTIME.h"
#include "forte/iec61131_functions/func_SUB_LTOD_LTIME.h"
#include "forte/iec61131_functions/func_SUB_LTOD_LTOD.h"
#include "forte/iec61131_functions/func_SUB_TIME.h"
#include "forte/iec61131_functions/func_SUB_TOD_TIME.h"
#include "forte/iec61131_functions/func_SUB_TOD_TOD.h"
#include "forte/iec61131_functions/func_TAN.h"
#include "forte/iec61131_functions/func_TOLOWER.h"
#include "forte/iec61131_functions/func_TOUPPER.h"
#include "forte/iec61131_functions/func_TO_BIG_ENDIAN.h"
#include "forte/iec61131_functions/func_TO_LITTLE_ENDIAN.h"
#include "forte/iec61131_functions/func_TRUNC.h"
#include "forte/iec61131_functions/func_TRUNC_DINT.h"
#include "forte/iec61131_functions/func_TRUNC_INT.h"
#include "forte/iec61131_functions/func_TRUNC_LINT.h"
#include "forte/iec61131_functions/func_TRUNC_SINT.h"
#include "forte/iec61131_functions/func_TRUNC_UDINT.h"
#include "forte/iec61131_functions/func_TRUNC_UINT.h"
#include "forte/iec61131_functions/func_TRUNC_ULINT.h"
#include "forte/iec61131_functions/func_TRUNC_USINT.h"
#include "forte/iec61131_functions/func_UPPER_BOUND.h"
#include "forte/iec61131_functions/func_XOR.h"
