/*******************************************************************************
 * Copyright (c) 2026 HR Agartechnik GmbH
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Franz Höpfinger
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

// Some portions generated by Gemini CLI

#include "../../core/fbtests/fbtestfixture.h"

using namespace forte::literals;

namespace forte::iec61499::events::test {
  struct E_REND_TestFixture : public forte::test::CFBTestFixtureBase {
      static constexpr TEventID EI1 = 0;
      static constexpr TEventID EI2 = 1;
      static constexpr TEventID R = 2;
      static constexpr TEventID EO = 0;

      E_REND_TestFixture() : CFBTestFixtureBase("iec61499::events::E_REND"_STRID) {
        setup();
      }
  };

  BOOST_FIXTURE_TEST_SUITE(ERendTests, E_REND_TestFixture)

  BOOST_AUTO_TEST_CASE(Rendezvous_EI1_Then_EI2) {
    triggerEvent(EI1);
    BOOST_CHECK(eventChainEmpty());
    triggerEvent(EI2);
    BOOST_CHECK(checkForSingleOutputEventOccurence(EO));
  }

  BOOST_AUTO_TEST_CASE(Rendezvous_EI2_Then_EI1) {
    triggerEvent(EI2);
    BOOST_CHECK(eventChainEmpty());
    triggerEvent(EI1);
    BOOST_CHECK(checkForSingleOutputEventOccurence(EO));
  }

  BOOST_AUTO_TEST_CASE(Reset_From_EI1) {
    triggerEvent(EI1);
    BOOST_CHECK(eventChainEmpty());

    triggerEvent(R);
    BOOST_CHECK(eventChainEmpty());

    // After reset, triggering the other one (EI2) should not cause EO
    triggerEvent(EI2);
    BOOST_CHECK(eventChainEmpty());

    // Triggering EI1 now should cause EO
    triggerEvent(EI1);
    BOOST_CHECK(checkForSingleOutputEventOccurence(EO));
  }

  BOOST_AUTO_TEST_CASE(Reset_From_EI2) {
    triggerEvent(EI2);
    BOOST_CHECK(eventChainEmpty());

    triggerEvent(R);
    BOOST_CHECK(eventChainEmpty());

    // After reset, triggering the other one (EI1) should not cause EO
    triggerEvent(EI1);
    BOOST_CHECK(eventChainEmpty());

    // Triggering EI2 now should cause EO
    triggerEvent(EI2);
    BOOST_CHECK(checkForSingleOutputEventOccurence(EO));
  }

  BOOST_AUTO_TEST_CASE(Multiple_EI1_Then_Multiple_EI2) {
    triggerEvent(EI1);
    BOOST_CHECK(eventChainEmpty());
    triggerEvent(EI1);
    BOOST_CHECK(eventChainEmpty());
    triggerEvent(EI1);
    BOOST_CHECK(eventChainEmpty());

    // First EI2 completes the rendezvous
    triggerEvent(EI2);
    BOOST_CHECK(checkForSingleOutputEventOccurence(EO));

    // Subsequent EI2s without a new EI1 should not fire EO
    triggerEvent(EI2);
    BOOST_CHECK(eventChainEmpty());
    triggerEvent(EI2);
    BOOST_CHECK(eventChainEmpty());
  }

  BOOST_AUTO_TEST_CASE(Multiple_Rendezvous) {
    for (int i = 0; i < 5; i++) {
      triggerEvent(EI1);
      BOOST_CHECK(eventChainEmpty());
      triggerEvent(EI2);
      BOOST_CHECK(checkForSingleOutputEventOccurence(EO));
    }
  }

  BOOST_AUTO_TEST_SUITE_END()
} // namespace forte::iec61499::events::test
