/*******************************************************************************
 * Copyright (c) 2019, fortiss GmbH
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Jose Cabral - initial implementation
 *******************************************************************************/

#include "RegisterServiceOpcUa.h"

USE_STRING_ID(ANYToJSON);
USE_STRING_ID(APPEND_STRING_3);
USE_STRING_ID(CLIENT_1_0);
USE_STRING_ID(CNF);
USE_STRING_ID(CreateRegisterID);
USE_STRING_ID(CreateUnRegisterID);
USE_STRING_ID(CU);
USE_STRING_ID(CUO);
USE_STRING_ID(doneRegister);
USE_STRING_ID(doneUnregister);
USE_STRING_ID(DT);
USE_STRING_ID(E_CTU);
USE_STRING_ID(E_CTU_1);
USE_STRING_ID(E_DELAY);
USE_STRING_ID(E_DELAY_1);
USE_STRING_ID(EI);
USE_STRING_ID(endpoint);
USE_STRING_ID(EO);
USE_STRING_ID(EO0);
USE_STRING_ID(EO1);
USE_STRING_ID(E_PERMIT);
USE_STRING_ID(E_PERMIT_1);
USE_STRING_ID(E_SR);
USE_STRING_ID(E_SWITCH);
USE_STRING_ID(E_SWITCH_1);
USE_STRING_ID(E_SWITCH_1_1);
USE_STRING_ID(E_SWITCH_2);
USE_STRING_ID(F_STRING_TO_WSTRING);
USE_STRING_ID(F_STRING_TO_WSTRING_1);
USE_STRING_ID(G);
USE_STRING_ID(ID);
USE_STRING_ID(IN);
USE_STRING_ID(IN_1);
USE_STRING_ID(IN_2);
USE_STRING_ID(IN_3);
USE_STRING_ID(INIT);
USE_STRING_ID(InitFlagReg);
USE_STRING_ID(InitFlagUnReg);
USE_STRING_ID(INITO);
USE_STRING_ID(input);
USE_STRING_ID(OUT);
USE_STRING_ID(output);
USE_STRING_ID(PERMIT);
USE_STRING_ID(PV);
USE_STRING_ID(Q);
USE_STRING_ID(QI);
USE_STRING_ID(QO);
USE_STRING_ID(R);
USE_STRING_ID(Register);
USE_STRING_ID(registerService);
USE_STRING_ID(RegisterServiceAdp);
USE_STRING_ID(RegisterServiceOpcUa);
USE_STRING_ID(REQ);
USE_STRING_ID(S);
USE_STRING_ID(SD_1);
USE_STRING_ID(serviceRegistryEntry);
USE_STRING_ID(START);
USE_STRING_ID(Unregister);
USE_STRING_ID(unregisterService);


DEFINE_FIRMWARE_FB(FORTE_RegisterServiceOpcUa, STRID(RegisterServiceOpcUa))

const TForteInt16 FORTE_RegisterServiceOpcUa::scmEOWithIndexes[] = {-1};
const SAdapterInstanceDef FORTE_RegisterServiceOpcUa::scmAdapterInstances[] = {
{STRID(RegisterServiceAdp), STRID(registerService), false }};

const SFBInterfaceSpec FORTE_RegisterServiceOpcUa::scmFBInterfaceSpec = {
  0,  0, nullptr,  0,  0,
  0,  0, nullptr,   0, 0,  0,  0, 0, 
  0,  0, 0,
  1,scmAdapterInstances};


const SCFB_FBInstanceData FORTE_RegisterServiceOpcUa::scmInternalFBs[] = {
  {STRID(InitFlagReg), STRID(E_SR)},
  {STRID(E_PERMIT), STRID(E_PERMIT)},
  {STRID(CreateRegisterID), STRID(APPEND_STRING_3)},
  {STRID(F_STRING_TO_WSTRING), STRID(F_STRING_TO_WSTRING)},
  {STRID(E_PERMIT_1), STRID(E_PERMIT)},
  {STRID(InitFlagUnReg), STRID(E_SR)},
  {STRID(CreateUnRegisterID), STRID(APPEND_STRING_3)},
  {STRID(F_STRING_TO_WSTRING_1), STRID(F_STRING_TO_WSTRING)},
  {STRID(ANYToJSON), STRID(ANYToJSON)},
  {STRID(Register), STRID(CLIENT_1_0)},
  {STRID(Unregister), STRID(CLIENT_1_0)},
  {STRID(E_SWITCH), STRID(E_SWITCH)},
  {STRID(E_SWITCH_1), STRID(E_SWITCH)},
  {STRID(E_DELAY), STRID(E_DELAY)},
  {STRID(E_CTU), STRID(E_CTU)},
  {STRID(E_SWITCH_1_1), STRID(E_SWITCH)},
  {STRID(E_SWITCH_2), STRID(E_SWITCH)},
  {STRID(E_DELAY_1), STRID(E_DELAY)},
  {STRID(E_CTU_1), STRID(E_CTU)},
};

const SCFB_FBParameter FORTE_RegisterServiceOpcUa::scmParamters[] = {
  {2, STRID(IN_1), "STRING#opc_ua[CALL_METHOD; "},
  {2, STRID(IN_3), "STRING##; /Objects/2:ServiceRegistry/2:register]"},
  {6, STRID(IN_1), "STRING#opc_ua[CALL_METHOD; "},
  {6, STRID(IN_3), "STRING##; /Objects/2:ServiceRegistry/2:remove]"},
  {13, STRID(DT), "T#250ms"},
  {14, STRID(PV), "UINT#3"},
  {17, STRID(DT), "T#250ms"},
  {18, STRID(PV), "UINT#3"},
};

const SCFB_FBConnectionData FORTE_RegisterServiceOpcUa::scmEventConnections[] = {
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(CreateRegisterID), STRID(CNF)), 2, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(F_STRING_TO_WSTRING), STRID(REQ)), 3},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(F_STRING_TO_WSTRING), STRID(CNF)), 3, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(InitFlagReg), STRID(S)), 0},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(CreateUnRegisterID), STRID(CNF)), 6, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(F_STRING_TO_WSTRING_1), STRID(REQ)), 7},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(F_STRING_TO_WSTRING_1), STRID(CNF)), 7, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(InitFlagUnReg), STRID(S)), 5},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(registerService), STRID(registerService)), CCompositeFB::scmAdapterMarker |0, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(CreateRegisterID), STRID(REQ)), 2},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(registerService), STRID(unregisterService)), CCompositeFB::scmAdapterMarker |0, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(CreateUnRegisterID), STRID(REQ)), 6},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(InitFlagReg), STRID(EO)), 0, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Register), STRID(INIT)), 9},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_PERMIT), STRID(EO)), 1, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Register), STRID(REQ)), 9},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Register), STRID(INITO)), 9, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_PERMIT), STRID(EI)), 1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(InitFlagUnReg), STRID(EO)), 5, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Unregister), STRID(INIT)), 10},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_PERMIT_1), STRID(EO)), 4, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Unregister), STRID(REQ)), 10},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Unregister), STRID(INITO)), 10, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_PERMIT_1), STRID(EI)), 4},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_CTU), STRID(CUO)), 14, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_SWITCH_1), STRID(EI)), 12},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_SWITCH_1), STRID(EO0)), 12, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_DELAY), STRID(START)), 13},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_SWITCH), STRID(EO0)), 11, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_CTU), STRID(CU)), 14},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_SWITCH), STRID(EO1)), 11, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(InitFlagReg), STRID(R)), 0},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Register), STRID(CNF)), 9, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_SWITCH), STRID(EI)), 11},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_DELAY), STRID(EO)), 13, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Register), STRID(REQ)), 9},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_SWITCH_1_1), STRID(EO0)), 15, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_DELAY_1), STRID(START)), 17},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_CTU_1), STRID(CUO)), 18, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_SWITCH_1_1), STRID(EI)), 15},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_SWITCH_2), STRID(EO0)), 16, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_CTU_1), STRID(CU)), 18},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_SWITCH_2), STRID(EO1)), 16, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(InitFlagUnReg), STRID(R)), 5},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Unregister), STRID(CNF)), 10, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_SWITCH_2), STRID(EI)), 16},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_DELAY_1), STRID(EO)), 17, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Unregister), STRID(REQ)), 10},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_SWITCH_1_1), STRID(EO1)), 15, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(InitFlagUnReg), STRID(R)), 5},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_SWITCH_1), STRID(EO1)), 12, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(InitFlagReg), STRID(R)), 0},
};

const SCFB_FBFannedOutConnectionData FORTE_RegisterServiceOpcUa::scmFannedOutEventConnections[] = {
  {1, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(ANYToJSON), STRID(REQ)), 8},
  {3, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(ANYToJSON), STRID(REQ)), 8},
  {15, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(registerService), STRID(doneRegister)), CCompositeFB::scmAdapterMarker |0},
  {15, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_CTU), STRID(R)), 14},
  {21, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(registerService), STRID(doneUnregister)), CCompositeFB::scmAdapterMarker |0},
  {21, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_CTU_1), STRID(R)), 18},
  {24, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(registerService), STRID(doneUnregister)), CCompositeFB::scmAdapterMarker |0},
  {24, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_CTU_1), STRID(R)), 18},
  {25, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(registerService), STRID(doneRegister)), CCompositeFB::scmAdapterMarker |0},
  {25, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_CTU), STRID(R)), 14},
};

const SCFB_FBConnectionData FORTE_RegisterServiceOpcUa::scmDataConnections[] = {
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(InitFlagReg), STRID(Q)), 0, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_PERMIT), STRID(PERMIT)), 1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(CreateRegisterID), STRID(OUT)), 2, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(F_STRING_TO_WSTRING), STRID(IN)), 3},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(CreateUnRegisterID), STRID(OUT)), 6, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(F_STRING_TO_WSTRING_1), STRID(IN)), 7},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(InitFlagUnReg), STRID(Q)), 5, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_PERMIT_1), STRID(PERMIT)), 4},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(registerService), STRID(serviceRegistryEntry)), CCompositeFB::scmAdapterMarker |0, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(ANYToJSON), STRID(input)), 8},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(registerService), STRID(endpoint)), CCompositeFB::scmAdapterMarker |0, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(CreateRegisterID), STRID(IN_2)), 2},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(F_STRING_TO_WSTRING), STRID(OUT)), 3, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Register), STRID(ID)), 9},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(ANYToJSON), STRID(output)), 8, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Register), STRID(SD_1)), 9},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(F_STRING_TO_WSTRING_1), STRID(OUT)), 7, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Unregister), STRID(ID)), 10},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_CTU), STRID(Q)), 14, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_SWITCH_1), STRID(G)), 12},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Register), STRID(QO)), 9, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_SWITCH), STRID(G)), 11},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_CTU_1), STRID(Q)), 18, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_SWITCH_1_1), STRID(G)), 15},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Unregister), STRID(QO)), 10, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(E_SWITCH_2), STRID(G)), 16},
};

const SCFB_FBFannedOutConnectionData FORTE_RegisterServiceOpcUa::scmFannedOutDataConnections[] = {
  {0, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Register), STRID(QI)), 9},
  {3, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Unregister), STRID(QI)), 10},
  {5, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(CreateUnRegisterID), STRID(IN_2)), 6},
  {7, GENERATE_CONNECTION_PORT_ID_2_ARG(STRID(Unregister), STRID(SD_1)), 10},
};

const SCFB_FBNData FORTE_RegisterServiceOpcUa::scmFBNData = {
  19, scmInternalFBs,
  26, scmEventConnections,
  10, scmFannedOutEventConnections,
  13, scmDataConnections,
  4, scmFannedOutDataConnections,
  0, nullptr,
  8, scmParamters
};


