name: Clang Format Check

on:
  push:
    branches: [ "release", "develop", "freeze", "feature/**" ]
  pull_request:
    branches: [ "release", "develop", "freeze", "feature/**" ]

jobs:
  clang-format:
    name: Check Clang Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Find all source
        id: find_sources
        run: |
          FILES=$(find src/ -type f \( -name "*.cpp" -o -name "*.cc" -o -name "*.c" -o -name "*.h" -o -name "*.hpp" \))
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Run clang-format check
        run: |
          echo "${{ steps.find_sources.outputs.files }}" | xargs clang-format --dry-run --Werror

