name: Clang Format Check

on:
  push:
    branches: [ "release", "develop", "freeze", "feature/**" ]
  pull_request:
    branches: [ "release", "develop", "freeze", "feature/**" ]

jobs:
  clang-format:
    name: Check Clang Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get install -y clang-format
      
      - name: Run clang-format check script
        run: ./checkstyle.sh

